name: 'Action_zhKong_composite'
description: 'Action'
inputs:
  ROUTER_MODEL:  
    description: 'MODEL'
    required: true
    default: 'AX6'
  COMPILE_CONFIG: 
    description: 'CONFIG'
    required: true
    default: 'AX6-20240325-avahi'
  FILES_CONFIG: 
    description: 
    required: false
    default: 'public'
#   PATH: 
#    description: 
#    required: true
#    default: 'public'   
#outputs:
#  random-number:
#    description: "Random number"
#    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Show system
      shell: bash
      env:
        ROUTER_MODEL.: ${{ inputs.ROUTER_MODEL }}   
        COMPILE_CONFIG: ${{ inputs.COMPILE_CONFIG }} 
        FILES_CONFIG: ${{ inputs.FILES_CONFIG }}       
      run: |
          mkdir OpenWRT-Action
          mkdir OpenWRT-Action/openwrt
          mkdir OpenWRT-Action/openwrt/bin
          mkdir OpenWRT-Action/openwrt/bin/targets
          touch OpenWRT-Action/openwrt/bin/targets/test.sysupgrade.bin
          echo '当前执行步骤：5-打标'
          if [ "$FILES_CONFIG" != 'public' ] ; then
             tag_name=$COMPILE_CONFIG-$FILES_CONFIG
          else
             tag_name=$COMPILE_CONFIG
          fi
          tag_name=$tag_name-$(date +%Y%m%d-%H%M)
          echo $tag_name
          echo "TAG_NAME=$tag_name" >> $GITHUB_ENV  

    - name: Organize files      
      shell: bash
      run: |                             
          echo '当前执行步骤：6-组织产出文件'
          echo "当前工作目录"
          pwd
          tree -L 4
          cd ./OpenWRT-Action
          rm -rf ./artifact/
          mkdir -p ./artifact/
          cp -vrf $(find ./openwrt/bin/targets/ -type f -name "*sysupgrade*") ./artifact/
          cp -vrf $(find ./openwrt/bin/targets/ -type f -name "*.buildinfo") ./artifact/
          cp -vr ./openwrt/.config ./artifact/defconfig-$COMPILE_CONFIG.config
          cd ./artifact/
          rename 's/sysupgrade.bin/sysupgrade-${{ env.TAG_NAME }}.bin/' *
          ls -Ahl
          
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: OpenWrt-${{ env.COMPILE_CONFIG }}-${{ env.FILES_CONFIG }}-${{ env.TAG_NAME }}
        path: ./OpenWRT-Action/artifact/
