name: 'Action_zhKong_composite'
description: 'Action'
inputs:
  ROUTER_MODEL:  
    description: 'MODEL'
    required: true
    default: 'AX6'
  COMPILE_CONFIG: 
    description: 'CONFIG'
    required: true
    default: 'AX6-20240325-avahi'
  FILES_CONFIG: 
    description: 
    required: false
    default: 'public'
runs:
  using: "composite"
  steps:
    - name: Compile      
      shell: bash
      env:
        ROUTER_MODEL.: ${{ inputs.ROUTER_MODEL }}   
        COMPILE_CONFIG: ${{ inputs.COMPILE_CONFIG }} 
        FILES_CONFIG: ${{ inputs.FILES_CONFIG }} 
      run:  |
          echo "当前工作目录"
          pwd          
          #cd PATH         
          echo '当前执行步骤：1-下载AgustinLorenzo/openwrt仓库'
          git clone --depth 1  https://github.com/thinkcyy/OpenWRT-Action OpenWRT-Action 
          git clone --depth 1  https://github.com/AgustinLorenzo/openwrt -b main --single-branch ./OpenWRT-Action/openwrt
          tree -L 3
          
          echo '当前执行步骤：2-处理Package'
          cd ./OpenWRT-Action
          echo "当前工作目录"
          pwd 
          tree -L 3
          chmod +x ./zhKong/scripts/*.sh
          cp -vr ./zhKong/config/$COMPILE_CONFIG.config ./zhKong/config/config-$ROUTER_MODEL.config
          ./zhKong/scripts/prepare.sh
          
          echo '当前执行步骤：3-添加自定义配置files'
          #echo $FILES_CONFIG
          if [ "$FILES_CONFIG" != 'public' ] ; then
             echo "files版本为$FILES_CONFIG"
             cp -vr ../openwrt-config/common/files ./openwrt/
             cp -vr ../openwrt-config/common/$FILES_CONFIG/files ./openwrt/
             cp -vr ../openwrt-config/$ROUTER_MODEL/common/files ./openwrt/
             cp -vr ../openwrt-config/$ROUTER_MODEL/$FILES_CONFIG/files ./openwrt/
             chmod +x ./openwrt/files/etc/tinc/tincvpn/tinc-up
             chmod +x ./openwrt/files/etc/tinc/tincvpn/tinc-down
          else
             echo '-当前为public版本，跳过'
          fi          
          
          echo '当前执行步骤：4-编译'
          cd ./openwrt
          echo '当前执行步骤：4.1-下载'
          make download -j$(nproc)
          echo '当前执行步骤：4.2-编译'
          make -j$(nproc) || make -j1 V=s
          
          echo '当前执行步骤：5-打标'
          if [ "$FILES_CONFIG" != 'public' ] ; then
             tag_name=$COMPILE_CONFIG-$FILES_CONFIG
          else
             tag_name=$COMPILE_CONFIG
          fi
          tag_name=$tag_name-$(date +%Y%m%d-%H%M)
          echo $tag_name
          echo "TAG_NAME=$tag_name" >> $GITHUB_ENV  

    - name: Organize files      
      shell: bash
      run: |                             
          echo '当前执行步骤：6-组织产出文件'
          echo "当前工作目录"
          pwd
          cd ./OpenWRT-Action
          rm -rf ./artifact/
          mkdir -p ./artifact/
          cp -vrf $(find ./openwrt/bin/targets/ -type f -name "*sysupgrade*") ./artifact/
          cp -vrf $(find ./openwrt/bin/targets/ -type f -name "*.buildinfo") ./artifact/
          cp -vr ./openwrt/.config ./artifact/defconfig-$COMPILE_CONFIG.config
          cd ./artifact/
          rename 's/sysupgrade.bin/sysupgrade-${{ env.TAG_NAME }}.bin/' *
          ls -Ahl
          
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: OpenWrt-${{ env.TAG_NAME }}
        path: ./OpenWRT-Action/artifact/
